server:
    port: 8082
spring:
    application:
        name: user-service
    datasource:
        password: password
        url: jdbc:postgresql://localhost:5432/user
        username: user

    flyway:
        create-schemas: true
        schemas: shared

    jackson:
        deserialization:
            accept-empty-array-as-null-object: true
            accept-empty-string-as-null-object: true

    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                jdbc:
                    time_zone: UTC
        show-sql: false
